export default {
    dateTimeFields: ['date', 'datetime', 'dateTime', 'dateTimeLocal'],
    dateTimeExportFormat: ' hh:mm:ss A',
    dateTimeCSVExportFormat: '-hh:mm:ss A',
    dateTimeISOFormat: "YYYY-MM-DDTHH:mm:ss",
    filterDateFormat: "YYYY-MM-DD HH:mm:ss",
    fullDateFormat: "YYYYMMDDHHmmssSSS",
    dateTimeExcelExportFormat: ' hh:mm:ss AM/PM',
    dateTimeExcelRowExportFormat: ' hh:mm:ss A',
    ENTRA_APP_STAGES: {
        SIGN_IN: 'sign_in',
        PASSWORD_RESET: 'password_reset',
        EDIT_PROFILE: 'edit_profile',
        ACQUIRE_TOKEN: 'acquire_token'
    },
    authMethods: {
        basicAuth: 'basicAuth',
        entraIdAuth: 'entraIdAuth'
    },
    uploadCaptureUrl: '/auditsurvey/uploadCapture',
    LookupType: {
        Manufaturer: -1,
        LocationCode: -2,
        ParentAssetType: -3,
        AssetType: -4,
        Planogram: -5,
        Role: -6,
        LocationClassification: -7,
        Distributor: -8,
        Country: -9,
        SalesPerson: -10,
        ClientUserType: -11,
        TimeZone: -12,
        RouteType: -13,
        ProductCategory: -14,
        ExternalAssetCode: -15,
        Asset: -16,
        Product: -17,
        ClientUserLookup: -18,
        Market: 38,
        PreferedNotificationType: 59,
        ProductType: 62,
        ReplenishModel: 102,
        KeyAccountType: 114,
        EmployerType: 115,
        ProductSecondCategoryType: 116,
        OrientationType: 134,
        DoorHandleLocationType: 135,
        SubscriptionType: 158,
        AlertUserLookup: -19,
    },
    PermissionType: {
        Module: 0,
        Add: 1,
        Edit: 2,
        Delete: 3,
        Export: 4,
        Tag: 5
    },
    elasticHitsMaxSize: 10000,
    reportFolder: "attachments"
}